### ISSUE TITLE
Reproducing quantitative results

### ISSUE THREAD

**Issue by thadikari** [musyoku/adversarial-autoencoder#13]
Hi musyoku,
Thank you very much for the code. I ran your implementation and was able to get the reported results in README.md.
However my question is, have you been able to reach an error rate of 1.90 (±0:10)% for MNIST 100 labels (as reported in original paper)? Even after 5000 epochs the lowest I get is somewhat around 5%.

**Comment by musyoku** [comment]
Hi.
I have not reached it.
