### ISSUE TITLE
Errors while running codes

### ISSUE THREAD

**Issue by gagb** [musyoku/adversarial-autoencoder#6]
Hi,

I get the following error message when I try to run `unsupervised/clustering/train.py`
<img width="717" alt="screen shot 2017-03-15 at 11 10 28 pm" src="https://cloud.githubusercontent.com/assets/13227607/23984050/9f736db8-09d4-11e7-8ddd-7ba3bc43c88e.png">

And I get the follwing message when I try to run `supervised/learn_style/train.py`
<img width="720" alt="screen shot 2017-03-15 at 11 15 57 pm" src="https://cloud.githubusercontent.com/assets/13227607/23984184/659894fa-09d5-11e7-95f7-12c2ebad878f.png">

I am able to run `semi-supervised/regularize_z/train.py` successfully though. Thanks in advance!

**Comment by musyoku** [comment]
HI.
I fixed the code and trained a model for several epochs.

![clusters](https://cloud.githubusercontent.com/assets/15250418/23994177/0b1aec0a-0a87-11e7-8e21-99295276bd6d.png)
![analogy](https://cloud.githubusercontent.com/assets/15250418/23994215/355a0a82-0a87-11e7-96ad-a3fadf0d5a2b.png)

Thank you :smile:

**Comment by gagb** [comment]
The issue seems to be fixed.
Thanks!
