### ISSUE TITLE
Errors while running codes

### ISSUE THREAD

**Issue by Abraham0912541** [musyoku/adversarial-autoencoder#9]
Hi,

I get the following error message when I try to run supervised/train.py

![default](https://user-images.githubusercontent.com/27407417/30430091-a199ddbe-998c-11e7-9424-e57fde6a8dd7.PNG)
I want to run it successfully. Thank you in advance!

**Comment by jgw2000** [comment]
I have encountered the same mistake with you, have you solved this problem?

**Comment by SuJingZhi** [comment]
Sorry，I have no idea to solve this issue.

**Comment by EtienneDesticourt** [comment]
The chainer API changed since this project was written, chainer/chainer#2185 removed the bias argument and replaced it by initial_bias.
Replace line 169 of layers.py by `self.initial_bias = bias` and it should work.

**Comment by Abraham0912541** [comment]
Thank you very much！
